export const quotesData = [
  {
    emotionTags: ["happy"],
    isIspirational: true,
    image: "happy.jpg",
    alt: "quote: and she finally chose herself this time.",
  },
  {
    emotionTags: ["happy"],
    isIspirational: false,
    image: "happy2.jpg",
    alt: "quote: I find it kind of beautiful that everyone who has ever lived has seen the same sun.",
  },
  {
    emotionTags: ["happy"],
    isIspirational: true,
    image: "happy3.jpg",
    alt: "quote: Be happy, not because everything is good, but you can see the good side of everything.",
  },
  {
    emotionTags: ["inlove"],
    isIspirational: false,
    image: "inlove.jpg",
    alt: "quote: I knew I did from that first moment we met. It was not love at first sight exactly, but - familiarity. Like: oh, hello, it's you. It's going to be you.",
  },
  {
    emotionTags: ["inlove"],
    isIspirational: true,
    image: "inlove2.jpg",
    alt: "quote: Don't worry. One day we will sit together and with grateful hearts, we will say, 'it was hard but we made it. It was all worth it.'",
  },
  {
    emotionTags: ["inlove"],
    isIspirational: true,
    image: "inlove3.jpg",
    alt: "quote: I see it. I see us getting married, moving in together. I see all of it. See both of us together, forever.",
  },
  {
    emotionTags: ["thankful"],
    isIspirational: true,
    image: "thankful.jpg",
    alt: "quote: It is a serious thing, just to be alive on this fresh morning in this broken world.",
  },
  {
    emotionTags: ["hopeful"],
    isIspirational: true,
    image: "hopeful.jpg",
    alt: "quote: Maybe the journey isn't so much about becoming anything. Maybe it's about unbecoming everything that isn't really you, so you can be who you were meant to be in the first place.",
  },
  {
    emotionTags: ["hopeful"],
    isIspirational: true,
    image: "hopeful2.jpg",
    alt: "quote: Your first work out will be bad. Your first podcast will be bad. Your first speech will be bad. Your first video will be bad. Your first anything will be bad. But you can't make your 100th without making your first. So put your ego aside and start.",
  },
  {
    emotionTags: ["hopeful"],
    isIspirational: true,
    image: "hopeful3.jpg",
    alt: "quote: It's okay to start over and over and over and over and over.",
  },
  {
    emotionTags: ["angry"],
    isIspirational: false,
    image: "angry.jpg",
    alt: "quote: How many graves will I need, to bury everything that died inside of me?",
  },
  {
    emotionTags: ["nonchalant"],
    isIspirational: false,
    image: "nonchalant.jpg",
    alt: "quote: Am I perfect? No. But am I striving to be a better person everyday? Also no.",
  },
  {
    emotionTags: ["nonchalant"],
    isIspirational: false,
    image: "nonchalant2.jpg",
    alt: "quote: If the truth shall kill them, let them die.",
  },
  {
    emotionTags: ["nonchalant"],
    isIspirational: false,
    image: "nonchalant3.jpg",
    alt: "quote: Bitch, don't kill my vibe.",
  },
  {
    emotionTags: ["sad"],
    isIspirational: false,
    image: "sad.jpg",
    alt: "quote: I think the biggest red flag in me is isolation. How I isolate myself when something is hurting me because I don't want to be a burden to someone. It's just that I prefer to cry in silence rather than beating the drums out loud.",
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "sad2.jpg",
    alt: "quote: How are you so quiet about it? Your sadness I mean. How do you hold it in your chest, in your eyes, in your teeth without letting it speak. How does it stay still?",
  },
  {
    emotionTags: ["sad"],
    isIspirational: false,
    image: "sad3.jpg",
    alt: "quote: Will you miss me like I'll miss you? Will you wonder how I've changed since I left? Will you keep being my home if I leave my heart behind?",
  },
  {
    emotionTags: ["depressed"],
    isIspirational: false,
    image: "depressed.jpg",
    alt: "quote: My thoughts were destroying me. I tried not to think, but the silence was a killer too.",
  },
  {
    emotionTags: ["depressed"],
    isIspirational: false,
    image: "depressed2.jpg",
    alt: "quote: I have always, essentially, been waiting. Waiting to become something else, waiting to be that person I always thought I was on the verge of becoming, waiting for that life I thought I would have. In my head, I was always one step away.",
  },
  {
    emotionTags: ["depressed"],
    isIspirational: false,
    image: "depressed3.jpg",
    alt: "quote: Real depression is when you stop loving the things you love.",
  },
  {
    emotionTags: ["anxious"],
    isIspirational: false,
    image: "anxiety.jpg",
    alt: "quote: Dear brain, stop overthinking. I am tired.",
  },
  {
    emotionTags: ["anxious"],
    isIspirational: true,
    image: "anxiety2.jpg",
    alt: "quote: Do not allow your anxiety about the world to fill your heart. If your heart is full of anxiety, you will get sick, and then you will not be able to help.",
  },
  {
    emotionTags: ["anxious"],
    isIspirational: false,
    image: "anxiety3.jpg",
    alt: "quote: Why do I have so many thoughts? They are driving me crazy. Why am I always going anywhere, instead of somewhere?",
  },
  {
    emotionTags: ["tired"],
    isIspirational: true,
    image: "tired.jpg",
    alt: "quote: Current status: tired but still trying.",
  },
  {
    emotionTags: ["tired"],
    isIspirational: false,
    image: "tired2.jpg",
    alt: "quote: Kinda tired of being okay with things I'm not okay with.",
  },
  {
    emotionTags: ["tired"],
    isIspirational: false,
    image: "tired3.jpg",
    alt: "quote: It's funny how people think your life is easy, just because you don't talk about teh things you go through.",
  },
  {
    emotionTags: ["alone"],
    isIspirational: false,
    image: "alone.jpg",
    alt: "quote: The worst feeling is having to suffer a panic attack aloneand telling yourself just a few more minutes and then it will be okay.",
  },
];
